### ISSUE TITLE
TypeError: t.validTypes is not iterable

### ISSUE THREAD

**Issue by mtripg6666tdr** [tsparticles/presets#101]
the breaking change introduced in https://github.com/tsparticles/tsparticles/commit/3cb697c8a3cf281591aab50e2a4a3aa2ae2eb900 (which changed the method signature of `Engine#addShape`) causes @tsparticles/preset-confetti not working. @tsparticles/preset-confetti is no longer compatible with @tsparticles/engine v3.4.0 (or maybe later). I confirmed @tsparticles/preset-confetti is broken, but other presets can be also broken.

![image](https://github.com/tsparticles/presets/assets/56076195/71abc485-261e-47c5-878b-6144bcd0b3f3)
![image](https://github.com/tsparticles/presets/assets/56076195/c5213488-8186-4f70-b590-0c47527b7430)

P.S. I thought which repository ( tsparticles/tsparticles or tsparticles/presets ) is appropriate where I should open the issue but I opened here. However in the aspect of the commit breaking semantic-versioning, the actual problem is likely to be in the tsparticles/tsparticles repository.

**Comment by matteobruni** [comment]
Released 3.1.0 with the new dependencies
